[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sphere-can-server"
version = "0.1.0"
description = "SPHERE CAN control server"
requires-python = ">=3.9"
dependencies = [
    "fastapi",
    "uvicorn",
    "python-can",
    "pyserial",
]

[tool.setuptools.packages.find]
where = ["."]

